
package com.ing.ide.main.playwrightrecording;

import static com.ing.engine.constants.ObjectAttribute.frame;
import com.ing.ide.main.utils.Utils;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.time.Duration;
import java.time.Instant;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class PlaywrightSpinner extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form PlaywriteSpinnerFinal
     */
    boolean closeFlag=false;
    public PlaywrightSpinner() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Image icon=new ImageIcon(Utils.class.getResource("/playwrightrecorder/ImportPlaywrightRecordingMenu.png")).getImage();
        
        setIconImage(icon);
        addWindowListener(new WindowAdapter() {
            //I skipped unused callbacks for readability
            @Override
            public void windowClosing(WindowEvent e) { 
                    closeFlag=true;
                    setVisible(false);
                    dispose(); 
                    
                    
            }
        });
        Thread t=new Thread(this); 
        t.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(243, 239, 225));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Please wait while the Playwright Recorder is being loaded");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(350, 180));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(80);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMaximumSize(new java.awt.Dimension(32767, 32767));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/playwrightrecorder/loading_resized_25x25.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(163, 117));
        jLabel2.setMinimumSize(new java.awt.Dimension(163, 117));
        jLabel2.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(620, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public void appendLog(String message) {
        jTextArea1.append(message + "\n");
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaywrightSpinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaywrightSpinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaywrightSpinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaywrightSpinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaywrightSpinner().setVisible(true);  
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
         boolean playwrightFlag=false;
          Instant start = Instant.now();
          
          
        while(!playwrightFlag&&!closeFlag)  
        {  Duration timeElapsed;
      
        
        try {
             Instant end = Instant.now();
             timeElapsed = Duration.between(start, end);
             String os = System.getProperty("os.name").toLowerCase();
             String[] command = new String[0];
             Process process;
            if (os.contains("win")) {
                // Windows specific command
                process = Runtime.getRuntime().exec("cmd /c tasklist /fi \"windowtitle eq Playwright*\"");
                command = new String[]{"cmd", "/c", "mvn initialize -f engine/pom.xml ^&^& mvn exec:java -f engine/pom.xml -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="};
            } else if (os.contains("mac")) {
                // Mac specific command
                process = Runtime.getRuntime().exec(new String[] { "sh", "-c", "ps -ef | grep 'playwright_chromium'" });
                command = new String[]{"bash", "-l", "-c", "mvn initialize -f engine/pom.xml && mvn exec:java -f engine/pom.xml -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="};
            } else {
                throw new UnsupportedOperationException("Unsupported operating system: " + os);
            }

             Process processLogs = Runtime.getRuntime().exec(command);
             InputStream taskListStream = process.getInputStream();
             InputStream taskListStreamLogs = processLogs.getInputStream();
             InputStreamReader streamReader = new InputStreamReader(taskListStream);
             InputStreamReader streamReaderLogs = new InputStreamReader(taskListStreamLogs);
             BufferedReader tasks = new BufferedReader(streamReader);
             BufferedReader tasksLogs = new BufferedReader(streamReaderLogs);
             String line = null;
             String lineLogs = null;
            
            while ((line = tasks.readLine()) != null) {
                while ((lineLogs = tasksLogs.readLine()) != null) {
                    appendLog(lineLogs);
                    if (lineLogs.contains("(default-cli)"))
                        break;
                    if(line.contains("chrome.exe") || line.contains("playwright_chromiumdev")){   
                    playwrightFlag=true;
                    dispose();
                    break;
                    }
                }
                break;
            }

        if((int)timeElapsed.getSeconds()>=150&&!playwrightFlag)
        {
           dispose();
           LoadingFail b=new LoadingFail();
           b.setAlwaysOnTop(true);
           b.setVisible(true);
           break;
        
        }
        } catch (Exception ex) {
            //    Logger.getLogger(PlaywriteLoadingFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        }
        }
}
